### ISSUE TITLE
Pin to known working commit of nvidia-docker instead of master

### ISSUE THREAD

**Issue by thibaudh** [graphistry/infrastructure#3]
I am worried that our users may not "enjoy the trill of nvidia-docker master".  Some customers may deploy a Graphistry release a couple of months after we build it. If nvidia-docker is in the middle of a big breakage, that could be problematic.

Until nvidia-docker does proper releases, I suggest we pin to known working commit.

**Comment by lmeyerov** [comment]
`nvidia-docker master` seems to be moving quickly and I suspect we rather not deal with older versions. 

In terms of gov users, I think it's fair to say we keep changing, per-release, until the end of Phase II. We need some form of API compatibility from Phase 1 onwards, but I don't think this needs to be part of that.

**Comment by lmeyerov** [comment]
Worth noting: at some point, switching to quarterly release for on-premise seems fair. For early adopters, dealing with change is part of the price of getting early access & ability to influence our direction.

**Comment by lsb** [comment]
Fixed via https://github.com/graphistry/infrastructure/commit/d8feb37ea6f38faa0ce21c75f7f8e581142b456e

**Comment by lsb** [comment]
These are the instructions at the front readme of the nvidia docker project :)
